### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by bhaskar1001101** [GDSC-IIIT-Kalyani/hacktoberfest-23#1]
We need a CONTRIBUTING.md to explain to newcomers how to get started with contributing to this repository.

**Comment by samyxandz** [comment]
hey there bhasky
i would love to work on making a CONTRIBUTING.md for this repo
it would be great if you could assign it to me

**Comment by samyxandz** [comment]
thank you so much for the issue!
